---
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - 
        name: Chekout code
        uses: actions/checkout@v2 
      - 
        name: Create env file
        run: |
          cd web-ui &&
          touch .env
          echo REACT_APP_POLYGON_EDGE_API=https://rpc-edgenet.polygon.technology >> .env
          echo REACT_APP_POLYGON_EDGE_CHAIN_ID=0x64 >> .env
          echo REACT_APP_STAKEOVERFLOW_CONTRACT_ADDRESS=0x39Ae75233F54985440F7139e1B0bc1BDCa2E67b9 >> .env
          echo REACT_APP_IPFS_API_URL=https://ipfs.infura.io:5001/api/v0 >> .env
          echo REACT_APP_GRAPH_URL=https://graph.stakeoverflow.net:8000/subgraphs/name/NewStakeOverflow >> .env
      - 
        name: Build frontend
        run: |
          cd web-ui && npm install && CI=false yarn build

  

  