---
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - 
        name: Chekout code
        uses: actions/checkout@v2
      - 
        name: Build frontend
        run: |
          cd web-ui && npm install && yarn build

  

  